/* ============================
   MODULE: Database (db.js)
   ============================ */
const DB = {
    alignments: [
        "Lawful Good", "Neutral Good", "Chaotic Good",
        "Lawful Neutral", "True Neutral", "Chaotic Neutral",
        "Lawful Evil", "Neutral Evil", "Chaotic Evil"
    ],

    races: {
        "Human": { min_str: 3, max_str: 18, min_dex: 3, max_dex: 18, min_con: 3, max_con: 18, min_int: 3, max_int: 18, min_wis: 3, max_wis: 18, min_cha: 3, max_cha: 18, classes: ["Fighter","Paladin","Ranger","Mage","Specialist Wizard","Cleric","Druid","Thief","Bard"], infravision: 0, languages: ["Common"], special: "None", size: "M" },
        "Elf": { min_str: 3, max_str: 18, min_dex: 6, max_dex: 19, min_con: 7, max_con: 17, min_int: 8, max_int: 18, min_wis: 3, max_wis: 18, min_cha: 8, max_cha: 18, classes: ["Fighter","Ranger","Mage","Specialist Wizard","Cleric","Thief","Bard"], infravision: 60, languages: ["Common","Elvish"], special: "90% resistance to sleep/charm, secret door detection", size: "M" },
        "Dwarf": { min_str: 8, max_str: 18, min_dex: 3, max_dex: 17, min_con: 12, max_con: 19, min_int: 3, max_int: 18, min_wis: 3, max_wis: 18, min_cha: 3, max_cha: 17, classes: ["Fighter","Cleric","Thief"], infravision: 60, languages: ["Common","Dwarvish"], special: "+1 CON, -1 CHA, poison/disease/magic resistance, stonecunning", size: "S" },
        "Halfling": { min_str: 7, max_str: 17, min_dex: 7, max_dex: 19, min_con: 10, max_con: 18, min_int: 3, max_int: 18, min_wis: 3, max_wis: 18, min_cha: 3, max_cha: 18, classes: ["Fighter","Cleric","Thief"], infravision: 0, languages: ["Common","Halfling"], special: "+1 DEX, -1 STR, +1 to hit with slings/thrown weapons, saving throw bonus", size: "S" },
        "Gnome": { min_str: 6, max_str: 18, min_dex: 3, max_dex: 18, min_con: 8, max_con: 18, min_int: 6, max_int: 18, min_wis: 3, max_wis: 18, min_cha: 3, max_cha: 18, classes: ["Fighter","Cleric","Thief","Illusionist"], infravision: 60, languages: ["Common","Gnome"], special: "+1 INT, -1 WIS, speak with burrowing mammals, save bonus vs spells", size: "S" },
        "Half-Elf": { min_str: 3, max_str: 18, min_dex: 6, max_dex: 18, min_con: 6, max_con: 18, min_int: 4, max_int: 18, min_wis: 3, max_wis: 18, min_cha: 3, max_cha: 18, classes: ["Fighter","Ranger","Mage","Specialist Wizard","Cleric","Druid","Thief","Bard"], infravision: 60, languages: ["Common","Elvish"], special: "30% resistance to sleep/charm, secret door detection", size: "M" },
        "Half-Orc": { min_str: 6, max_str: 19, min_dex: 3, max_dex: 18, min_con: 13, max_con: 19, min_int: 3, max_int: 17, min_wis: 3, max_wis: 18, min_cha: 3, max_cha: 12, classes: ["Fighter","Cleric","Thief"], infravision: 60, languages: ["Common","Orcish"], special: "+1 STR, +1 CON, -2 CHA", size: "M" }
    },

    classes: {
        "Fighter": { hd: 10, thac0: [[1,20],[2,19],[3,18],[4,17],[5,16],[6,15],[7,14],[8,13],[9,12],[10,11],[11,10],[12,9],[13,8],[14,7],[15,6],[16,5],[17,4],[18,3],[19,2],[20,1]], saves: {ppdm: [16,14,13,12,11], rsw: [18,16,15,14,13], pp: [17,15,14,13,12], bw: [20,18,17,16,15], sp: [19,17,16,15,14]}, prof_slots: {weapon: 4, nonweapon: 3}, prof_advance: {weapon: 3, nonweapon: 3}, xp_table: [0,2000,4000,8000,16000,32000,64000,125000,250000,500000,750000,1000000,1250000,1500000,1750000,2000000,2250000,2500000,2750000,3000000], prime_req: "STR",
        requirements: { str: 9 }, alignment: ["Any"], multi: false, dual: true ,
        spell_slots: null},
        "Paladin": { hd: 10, thac0: [[1,20],[2,19],[3,18],[4,17],[5,16],[6,15],[7,14],[8,13],[9,12],[10,11],[11,10],[12,9],[13,8],[14,7],[15,6],[16,5],[17,4],[18,3],[19,2],[20,1]], saves: {ppdm: [14,12,11,10,9], rsw: [16,14,13,12,11], pp: [15,13,12,11,10], bw: [18,16,15,14,13], sp: [17,15,14,13,12]}, prof_slots: {weapon: 4, nonweapon: 3}, prof_advance: {weapon: 3, nonweapon: 3}, xp_table: [0,2250,4500,9000,18000,36000,70000,140000,280000,560000,840000,1120000,1400000,1680000,1960000,2240000,2520000,2800000,3080000,3360000], prime_req: "STR",
        requirements: { str: 12, dex: 9, con: 9, wis: 13, cha: 17 }, alignment: ["Lawful Good"], multi: false, dual: false, special: "Detect evil, +2 save, immune disease, lay on hands, aura protection, turn undead, divine spells" ,
        spell_slots: {type:"priest", offset:8, table:[[1],[2],[2,1],[3,2],[3,3,1],[3,3,2],[3,3,2,1],[3,3,3,2],[4,4,3,2,1]]}},
        "Ranger": { hd: 10, thac0: [[1,20],[2,19],[3,18],[4,17],[5,16],[6,15],[7,14],[8,13],[9,12],[10,11],[11,10],[12,9],[13,8],[14,7],[15,6],[16,5],[17,4],[18,3],[19,2],[20,1]], saves: {ppdm: [14,12,11,10,9], rsw: [16,14,13,12,11], pp: [15,13,12,11,10], bw: [18,16,15,14,13], sp: [17,15,14,13,12]}, prof_slots: {weapon: 4, nonweapon: 3}, prof_advance: {weapon: 3, nonweapon: 3}, xp_table: [0,2250,4500,9000,18000,36000,70000,140000,280000,560000,840000,1120000,1400000,1680000,1960000,2240000,2520000,2800000,3080000,3360000], prime_req: "STR/DEX/WIS",
        requirements: { str: 13, dex: 13, con: 14, wis: 14 }, alignment: ["Good"], multi: false, dual: false, special: "Tracking, favored enemy, surprise, animal empathy, hide in shadows/move silently, priest spells" ,
        spell_slots: {type:"priest", offset:7, table:[[1],[2],[2,1],[3,2],[3,3,1],[3,3,2],[3,3,2,1],[3,3,3,2],[4,4,3,2,1]]}},
        "Mage": { hd: 4, thac0: [[1,20],[2,20],[3,20],[4,19],[5,19],[6,19],[7,18],[8,18],[9,18],[10,17],[11,17],[12,17],[13,16],[14,16],[15,16],[16,15],[17,15],[18,15],[19,14],[20,14]], saves: {ppdm: [14,13,11,10,8], rsw: [11,9,7,5,3], pp: [13,11,9,7,5], bw: [15,13,11,9,7], sp: [12,10,8,6,4]}, prof_slots: {weapon: 1, nonweapon: 4}, prof_advance: {weapon: 6, nonweapon: 3}, xp_table: [0,2500,5000,10000,20000,40000,60000,90000,135000,250000,375000,750000,1125000,1500000,1875000,2250000,2625000,3000000,3375000,3750000], prime_req: "INT",
        requirements: { int: 9 }, alignment: ["Any"], multi: false, dual: false, special: "Spellcasting" ,
        spell_slots: {type:"wizard", table:[[1],[2],[2,1],[3,2],[4,2,1],[4,2,2],[4,3,2,1],[4,3,3,2],[4,3,3,2,1],[4,4,3,2,2],[4,4,4,3,3],[4,4,4,4,4,1],[5,5,5,4,4,2],[5,5,5,4,4,3,1],[5,5,5,5,5,4,2],[5,5,5,5,5,5,3,1],[5,5,5,5,5,5,3,2],[5,5,5,5,5,5,3,3],[5,5,5,5,5,5,4,3],[5,5,5,5,5,5,4,4]]}},
        "Specialist Wizard": { hd: 4, thac0: [[1,20],[2,20],[3,20],[4,19],[5,19],[6,19],[7,18],[8,18],[9,18],[10,17],[11,17],[12,17],[13,16],[14,16],[15,16],[16,15],[17,15],[18,15],[19,14],[20,14]], saves: {ppdm: [14,13,11,10,8], rsw: [11,9,7,5,3], pp: [13,11,9,7,5], bw: [15,13,11,9,7], sp: [12,10,8,6,4]}, prof_slots: {weapon: 1, nonweapon: 4}, prof_advance: {weapon: 6, nonweapon: 3}, xp_table: [0,2500,5000,10000,20000,40000,60000,90000,135000,250000,375000,750000,1125000,1500000,1875000,2250000,2625000,3000000,3375000,3750000], prime_req: "INT",
        requirements: { int: 9 }, alignment: ["Any"], multi: false, dual: false, special: "Specialist spell slot, +15% learn spell in school, -15% opposite school" ,
        spell_slots: {type:"wizard", table:[[1],[2],[2,1],[3,2],[4,2,1],[4,2,2],[4,3,2,1],[4,3,3,2],[4,3,3,2,1],[4,4,3,2,2],[4,4,4,3,3],[4,4,4,4,4,1],[5,5,5,4,4,2],[5,5,5,4,4,3,1],[5,5,5,5,5,4,2],[5,5,5,5,5,5,3,1],[5,5,5,5,5,5,3,2],[5,5,5,5,5,5,3,3],[5,5,5,5,5,5,4,3],[5,5,5,5,5,5,4,4]]}},
        "Cleric": { hd: 8, thac0: [[1,20],[2,19],[3,19],[4,18],[5,18],[6,17],[7,17],[8,16],[9,16],[10,15],[11,15],[12,14],[13,14],[14,13],[15,13],[16,12],[17,12],[18,11],[19,11],[20,10]], saves: {ppdm: [10,9,7,6,5], rsw: [14,13,11,10,9], pp: [13,12,10,9,8], bw: [16,15,13,12,11], sp: [15,14,12,11,10]}, prof_slots: {weapon: 2, nonweapon: 4}, prof_advance: {weapon: 4, nonweapon: 3}, xp_table: [0,1500,3000,6000,13000,27500,55000,110000,225000,450000,675000,900000,1125000,1350000,1575000,1800000,2025000,2250000,2475000,2700000], prime_req: "WIS",
        requirements: { wis: 9 }, alignment: ["Any"], multi: false, dual: true, special: "Turn undead, priest spells, bonus spells for high WIS" ,
        spell_slots: {type:"priest", table:[[1],[2],[2,1],[3,2],[3,3,1],[3,3,2],[3,3,2,1],[3,3,3,2],[4,4,3,2,1],[4,4,3,3,2],[5,4,4,3,2,1],[5,5,4,4,3,2],[5,5,5,4,4,3],[6,5,5,5,4,3,1],[6,6,5,5,4,4,2],[6,6,6,5,5,4,3],[6,6,6,6,5,5,4],[7,6,6,6,6,5,4,1],[7,7,6,6,6,5,5,2],[7,7,7,6,6,6,5,3]]}},
        "Druid": { hd: 8, thac0: [[1,20],[2,19],[3,19],[4,18],[5,18],[6,17],[7,17],[8,16],[9,16],[10,15],[11,15],[12,14],[13,14],[14,13],[15,13],[16,12],[17,12],[18,11],[19,11],[20,10]], saves: {ppdm: [10,9,7,6,5], rsw: [14,13,11,10,9], pp: [13,12,10,9,8], bw: [16,15,13,12,11], sp: [15,14,12,11,10]}, prof_slots: {weapon: 2, nonweapon: 4}, prof_advance: {weapon: 4, nonweapon: 3}, xp_table: [0,2000,4000,7500,12500,20000,35000,60000,100000,200000,400000,600000,800000,1000000,1200000,1400000,1600000,1800000,2000000,2200000], prime_req: "WIS",
        requirements: { wis: 12, cha: 15 }, alignment: ["True Neutral"], multi: false, dual: false, special: "Nature spells, shapechange, immunity to woodland charm, pass without trace" ,
        spell_slots: {type:"priest", table:[[1],[2],[2,1],[3,2],[3,3,1],[3,3,2],[3,3,2,1],[3,3,3,2],[4,4,3,2,1],[4,4,3,3,2],[5,4,4,3,2,1],[5,5,4,4,3,2],[5,5,5,4,4,3],[6,5,5,5,4,3,1],[6,6,5,5,4,4,2],[6,6,6,5,5,4,3],[6,6,6,6,5,5,4],[7,6,6,6,6,5,4,1],[7,7,6,6,6,5,5,2],[7,7,7,6,6,6,5,3]]}},
        "Thief": { hd: 6, thac0: [[1,20],[2,20],[3,19],[4,19],[5,18],[6,18],[7,17],[8,17],[9,16],[10,16],[11,15],[12,15],[13,14],[14,14],[15,13],[16,13],[17,12],[18,12],[19,11],[20,11]], saves: {ppdm: [13,12,11,10,9], rsw: [14,12,10,8,6], pp: [12,11,10,9,8], bw: [16,14,12,10,8], sp: [15,13,11,9,7]}, prof_slots: {weapon: 2, nonweapon: 3}, prof_advance: {weapon: 4, nonweapon: 4}, xp_table: [0,1250,2500,5000,10000,20000,40000,70000,110000,160000,220000,440000,660000,880000,1100000,1320000,1540000,1760000,1980000,2200000], prime_req: "DEX",
        requirements: { dex: 9 }, alignment: ["Any non-good"], multi: true, dual: true, special: "Backstab, thieving skills, read languages, use scrolls" ,
        spell_slots: null},
        "Bard": { hd: 6, thac0: [[1,20],[2,20],[3,19],[4,19],[5,18],[6,18],[7,17],[8,17],[9,16],[10,16],[11,15],[12,15],[13,14],[14,14],[15,13],[16,13],[17,12],[18,12],[19,11],[20,11]], saves: {ppdm: [13,12,11,10,9], rsw: [14,12,10,8,6], pp: [12,11,10,9,8], bw: [16,14,12,10,8], sp: [15,13,11,9,7]}, prof_slots: {weapon: 2, nonweapon: 3}, prof_advance: {weapon: 4, nonweapon: 4}, xp_table: [0,2000,4000,8000,16000,32000,64000,125000,250000,500000,750000,1000000,1250000,1500000,1750000,2000000,2250000,2500000,2750000,3000000], prime_req: "DEX/CHA",
        requirements: { dex: 12, int: 13, cha: 15 }, alignment: ["Any non-lawful"], multi: false, dual: false, special: "Bardic inspiration, legend lore, read languages, use magical devices, thief skills" ,
        spell_slots: {type:"wizard", offset:1, table:[[1],[2],[2,1],[3,2],[4,2,1],[4,2,2],[4,3,2,1],[4,3,3,2],[4,3,3,2,1],[4,4,3,2,2],[4,4,4,3,3],[4,4,4,4,4,1],[5,5,5,4,4,2],[5,5,5,4,4,3,1],[5,5,5,5,5,4,2],[5,5,5,5,5,5,3,1],[5,5,5,5,5,5,3,2],[5,5,5,5,5,5,3,3],[5,5,5,5,5,5,4,3],[5,5,5,5,5,5,4,4]]}}
    },

    kits: {
        "Fighter": [
            { name: "None", source: "PHB", desc: "Standard fighter." },
            { name: "Amazon", source: "CFH", desc: "Female warrior from matriarchal society. +1 reaction from females, -1 from males." },
            { name: "Barbarian", source: "CFH", desc: "Tribal warrior from uncivilized lands. Cannot be literate, immune to fear, wilderness survival." },
            { name: "Beast-Rider", source: "CFH", desc: "Mounted on exotic beasts. Special mount training." },
            { name: "Berserker", source: "CFH", desc: "Fights in battle frenzy. +2 hit/damage when raging, AC penalty, fatigue after." },
            { name: "Cavalier", source: "PHB", desc: "Mounted knight. Honor code, horsemanship, +1 reaction from nobility." },
            { name: "Gladiator", source: "CFH", desc: "Arena fighter. Specialization in specific weapons, crowd manipulation." },
            { name: "Myrmidon", source: "CFH", desc: "Professional soldier. Military tactics, command ability." },
            { name: "Noble Warrior", source: "CFH", desc: "Fighter of noble birth. Leadership, wealth, political connections." },
            { name: "Peasant Hero", source: "CFH", desc: "Commoner who rose to greatness. Disguise, rural contacts, -2 reaction from nobles." },
            { name: "Pirate/Outlaw", source: "CFH", desc: "Seafaring or wilderness outlaw. Navigation, seamanship, or tracking." },
            { name: "Savage", source: "CFH", desc: "Primitive warrior. Tattooing, spirit worship, tribal weapons." },
            { name: "Swashbuckler", source: "CFH", desc: "Dashing duelist. Acrobatics, climbing, taunting, armor restrictions." }
        ],
        "Paladin": [
            { name: "None", source: "PHB", desc: "Standard paladin." },
            { name: "Arms Dealer", source: "CPaH", desc: "Paladin who supplies righteous causes. Mercantile skills, contacts." },
            { name: "Divine Champion", source: "CPaH", desc: "Fanatical holy warrior. +1 vs evil, detect evil at will." },
            { name: "Envoy", source: "CPaH", desc: "Diplomatic paladin. Languages, etiquette, negotiation." },
            { name: "Equerry", source: "CPaH", desc: "Mounted holy knight. Special bonded mount, cavalry tactics." },
            { name: "Ghosthunter", source: "CPaH", desc: "Undead slayer. Turn undead as cleric 2 levels higher." },
            { name: "Inquisitor", source: "CPaH", desc: "Heresy hunter. Detect lie, interrogation, immunity to charm." },
            { name: "Medic", source: "CPaH", desc: "Healing paladin. Bonus healing, herbalism, delay poison." },
            { name: "Skyrider", source: "CPaH", desc: "Aerial paladin. Griffon/pegasus mount, aerial combat." },
            { name: "Wandering Paladin", source: "CPaH", desc: "Traveling do-gooder. Survival, no fixed church ties." }
        ],
        "Ranger": [
            { name: "None", source: "PHB", desc: "Standard ranger." },
            { name: "Beastmaster", source: "CRH", desc: "Animal companion. Train animals, 2 animal followers at 1st level." },
            { name: "Explorer", source: "CRH", desc: "Pathfinder and scout. Cartography, navigation, pathfinding." },
            { name: "Forest Runner", source: "CRH", desc: "Guerrilla fighter. Ambush, traps, woodland stealth." },
            { name: "Greenwood Ranger", source: "CRH", desc: "Forest guardian. Speak with plants, tree shape, forest spells." },
            { name: "Guardian", source: "CRH", desc: "Protector of a specific place. Alertness, local knowledge, territorial bonuses." },
            { name: "Justifier", source: "CRH", desc: "Lawful ranger. Tracking criminals, legal authority, urban survival." },
            { name: "Mountain Man", source: "CRH", desc: "Highland survivalist. Cold resistance, climbing, altitude adaptation." },
            { name: "Pathfinder", source: "CRH", desc: "Trailblazer. Never lost, find safe paths, guide others." },
            { name: "Sea Ranger", source: "CRH", desc: "Ocean ranger. Swimming, sailing, aquatic favored enemy." },
            { name: "Seeker", source: "CRH", desc: "Questing ranger. Lore, research, specific quest knowledge." },
            { name: "Stalker", source: "CRH", desc: "Urban hunter. Urban tracking, disguise, infiltration." },
            { name: "Warden", source: "CRH", desc: "Border guardian. Patrol, alarm, border law enforcement." }
        ],
        "Mage": [
            { name: "None", source: "PHB", desc: "Standard mage." },
            { name: "Academician", source: "CWH", desc: "Scholarly wizard. Research bonus, spellbook mastery, academic contacts." },
            { name: "Anagakok", source: "CWH", desc: "Arctic wizard. Cold spells, survival, spirit magic." },
            { name: "Amazon Sorceress", source: "CWH", desc: "Female battle mage. Combat spells, martial training." },
            { name: "Militant Wizard", source: "CWH", desc: "War mage. Military spells, command, tactical magic." },
            { name: "Patrician", source: "CWH", desc: "Noble wizard. Wealth, political influence, social spells." },
            { name: "Peasant Wizard", source: "CWH", desc: "Common-born mage. Disguise, low-born contacts, practical magic." },
            { name: "Savage Wizard", source: "CWH", desc: "Tribal shaman. Spirit magic, tribal lore, fetish crafting." },
            { name: "Witch", source: "CWH", desc: "Herbal and curse magic. Brewing, curses, familiar, healing." }
        ],
        "Specialist Wizard": [
            { name: "Abjurer", source: "PHB", desc: "Protection magic. +1 save vs abjuration, immune to hold/paralysis at high levels." },
            { name: "Conjurer", source: "PHB", desc: "Summoning magic. +1 save vs conjuration, extended summons." },
            { name: "Diviner", source: "PHB", desc: "Information magic. +1 save vs divination, detection mastery." },
            { name: "Enchanter", source: "PHB", desc: "Mind-affecting magic. +1 save vs enchantment, charm resistance." },
            { name: "Illusionist", source: "PHB", desc: "Deception magic. +1 save vs illusion, detect illusion." },
            { name: "Invoker", source: "PHB", desc: "Evocation magic. +1 save vs invocation, spell penetration." },
            { name: "Necromancer", source: "PHB", desc: "Death magic. +1 save vs necromancy, control undead." },
            { name: "Transmuter", source: "PHB", desc: "Change magic. +1 save vs transmutation, polymorph control." }
        ],
        "Cleric": [
            { name: "None", source: "PHB", desc: "Standard cleric." },
            { name: "Crusader", source: "CPrH", desc: "Military priest. Combat bonus, weapon specialization, war spells." },
            { name: "Fighting Monk", source: "CPrH", desc: "Martial artist priest. Unarmed combat, acrobatics, meditation." },
            { name: "Healer", source: "CPrH", desc: "Cure specialist. Bonus healing, herbalism, disease cure." },
            { name: "Missionary", source: "CPrH", desc: "Proselytizer. Languages, persuasion, conversion." },
            { name: "Oracle", source: "CPrH", desc: "Prophetic priest. Divination, augury, visions." },
            { name: "Pacifist Priest", source: "CPrH", desc: "Non-violent cleric. Cannot cause harm, powerful protection/healing." },
            { name: "Prophet", source: "CPrH", desc: "Voice of god. Command, fear aura, divine pronouncements." },
            { name: "Scholar Priest", source: "CPrH", desc: "Learned cleric. Ancient languages, lore, research." },
            { name: "Shaman", source: "CPrH", desc: "Tribal spirit-talker. Spirit contact, tribal magic, fetishes." },
            { name: "Wandering Mystic", source: "CPrH", desc: "Traveling holy person. Survival, no church ties, wandering spells." }
        ],
        "Druid": [
            { name: "None", source: "PHB", desc: "Standard druid." },
            { name: "Avenger", source: "CDH", desc: "Vengeful druid. Combat spells, tracking despoilers." },
            { name: "Druidic Knight", source: "CDH", desc: "Warrior druid. Armor allowed, combat training, nature war." },
            { name: "Forest Druid", source: "CDH", desc: "Woodland specialist. Tree spells, forest movement, sylvan allies." },
            { name: "Guardian of the Grove", source: "CDH", desc: "Sacred place defender. Location magic, alarm, territorial power." },
            { name: "Hermit", source: "CDH", desc: "Solitary druid. Meditation, extended shapechange, isolation powers." },
            { name: "Lost Druid", source: "CDH", desc: "Urban druid. City nature, sewers, parks, urban animals." },
            { name: "Pacifist Druid", source: "CDH", desc: "Non-violent nature priest. Cannot harm animals, powerful healing." },
            { name: "Savage Druid", source: "CDH", desc: "Primitive nature priest. Beast form, animal speech, totem magic." },
            { name: "Shapeshifter", source: "CDH", desc: "Master of forms. Extra shapechanges, hybrid forms, transformation." },
            { name: "Village Druid", source: "CDH", desc: "Community druid. Agriculture, weather, fertility, local spirits." }
        ],
        "Thief": [
            { name: "None", source: "PHB", desc: "Standard thief." },
            { name: "Assassin", source: "CTH", desc: "Killer for hire. Poison use, disguise, critical backstab." },
            { name: "Bandit", source: "CTH", desc: "Highway robber. Wilderness ambush, horsemanship, rural contacts." },
            { name: "Bounty Hunter", source: "CTH", desc: "Captures for reward. Tracking, manacles, non-lethal combat." },
            { name: "Burglar", source: "CTH", desc: "Breaking and entering. Lock mastery, trap detection, silent movement." },
            { name: "Cutpurse", source: "CTH", desc: "Pickpocket. Sleight of hand, crowd work, fence contacts." },
            { name: "Fence", source: "CTH", desc: "Stolen goods dealer. Appraisal, underworld contacts, laundering." },
            { name: "Smuggler", source: "CTH", desc: "Contraband runner. Concealment, customs evasion, transport." },
            { name: "Spy", source: "CTH", desc: "Information gatherer. Disguise, forgery, languages, infiltration." },
            { name: "Swindler", source: "CTH", desc: "Con artist. Fast-talk, forgery, gambling, disguise." },
            { name: "Troubleshooter", source: "CTH", desc: "Problem solver. Investigation, urban tracking, information." },
            { name: "Tunnel Rat", source: "CTH", desc: "Underground specialist. Underground navigation, darkvision, mapping." }
        ],
        "Bard": [
            { name: "None", source: "PHB", desc: "Standard bard." },
            { name: "Blade", source: "CBH", desc: "Dueling bard. Weapon specialization, swagger, challenge." },
            { name: "Charlatan", source: "CBH", desc: "Fake bard. Forgery, disguise, fast-talk, no real magic initially." },
            { name: "Gallant", source: "CBH", desc: "Romantic hero. Courtly love, poetry, dueling, noble contacts." },
            { name: "Gypsy Bard", source: "CBH", desc: "Traveling performer. Fortune telling, curses, caravan life." },
            { name: "Herald", source: "CBH", desc: "Official messenger. Etiquette, heraldry, diplomacy, news." },
            { name: "Jester", source: "CBH", desc: "Court fool. Mockery, tumbling, insult, surprising wisdom." },
            { name: "Loremaster", source: "CBH", desc: "Sage bard. Ancient lore, research, legend, identification." },
            { name: "Meistersinger", source: "CBH", desc: "Master performer. Performance mastery, composition, fame." },
            { name: "Riddlemaster", source: "CBH", desc: "Puzzle bard. Riddles, codes, cryptography, logic." },
            { name: "Skald", source: "CBH", desc: "Nordic bard. Battle poetry, berserker inspiration, sagas." }
        ]
    },

    weapons: [
        { name: "Battle Axe", cost: 5, weight: 7, size: "M", type: "S", speed: 7, damage_sm: "1d8", damage_l: "1d8", rof: null, range: null },
        { name: "Blowgun", cost: 5, weight: 2, size: "L", type: "P", speed: 5, damage_sm: "1d2", damage_l: "1d2", rof: 2, range: "10/20/30" },
        { name: "Club", cost: 0, weight: 3, size: "M", type: "B", speed: 4, damage_sm: "1d6", damage_l: "1d3", rof: null, range: "10/20/30" },
        { name: "Crossbow, Hand", cost: 300, weight: 3, size: "S", type: "P", speed: 5, damage_sm: "1d3", damage_l: "1d2", rof: 1, range: "20/40/60" },
        { name: "Crossbow, Heavy", cost: 50, weight: 14, size: "M", type: "P", speed: 10, damage_sm: "1d4+1", damage_l: "1d6+1", rof: 0.5, range: "80/160/240" },
        { name: "Crossbow, Light", cost: 35, weight: 7, size: "M", type: "P", speed: 7, damage_sm: "1d4", damage_l: "1d4", rof: 1, range: "60/120/180" },
        { name: "Dagger", cost: 2, weight: 1, size: "S", type: "P/S", speed: 2, damage_sm: "1d4", damage_l: "1d3", rof: 2, range: "10/20/30" },
        { name: "Dart", cost: 0.5, weight: 0.5, size: "S", type: "P", speed: 2, damage_sm: "1d3", damage_l: "1d2", rof: 3, range: "20/40/60" },
        { name: "Flail, Footman's", cost: 15, weight: 8, size: "M", type: "B", speed: 6, damage_sm: "1d6+1", damage_l: "2d4", rof: null, range: null },
        { name: "Flail, Horseman's", cost: 8, weight: 5, size: "M", type: "B", speed: 6, damage_sm: "1d4+1", damage_l: "1d4+1", rof: null, range: null },
        { name: "Halberd", cost: 10, weight: 15, size: "L", type: "P/S", speed: 9, damage_sm: "1d10", damage_l: "2d6", rof: null, range: null },
        { name: "Hammer, Throwing", cost: 1, weight: 4, size: "M", type: "B", speed: 4, damage_sm: "1d4+1", damage_l: "1d4", rof: 1, range: "10/20/30" },
        { name: "Hammer, War", cost: 2, weight: 6, size: "M", type: "B", speed: 4, damage_sm: "1d4+1", damage_l: "1d4", rof: null, range: null },
        { name: "Javelin", cost: 0.5, weight: 2, size: "M", type: "P", speed: 4, damage_sm: "1d6", damage_l: "1d6", rof: 1, range: "20/40/60" },
        { name: "Lance, Heavy", cost: 10, weight: 15, size: "L", type: "P", speed: 8, damage_sm: "1d6+1", damage_l: "2d6+1", rof: null, range: null },
        { name: "Lance, Light", cost: 6, weight: 5, size: "L", type: "P", speed: 6, damage_sm: "1d6", damage_l: "1d8", rof: null, range: null },
        { name: "Long Bow", cost: 75, weight: 3, size: "L", type: "P", speed: 8, damage_sm: "1d6", damage_l: "1d6", rof: 2, range: "70/140/210" },
        { name: "Long Sword", cost: 15, weight: 8, size: "M", type: "S/P", speed: 5, damage_sm: "1d8", damage_l: "1d12", rof: null, range: null },
        { name: "Mace, Footman's", cost: 8, weight: 10, size: "M", type: "B", speed: 7, damage_sm: "1d6+1", damage_l: "1d6", rof: null, range: null },
        { name: "Mace, Horseman's", cost: 5, weight: 6, size: "M", type: "B", speed: 6, damage_sm: "1d6", damage_l: "1d4", rof: null, range: null },
        { name: "Morning Star", cost: 10, weight: 12, size: "M", type: "B/P", speed: 8, damage_sm: "2d4", damage_l: "1d6+1", rof: null, range: null },
        { name: "Polearm", cost: 10, weight: 15, size: "L", type: "P", speed: 9, damage_sm: "1d10", damage_l: "1d10", rof: null, range: null },
        { name: "Quarterstaff", cost: 0.2, weight: 4, size: "L", type: "B", speed: 4, damage_sm: "1d6", damage_l: "1d6", rof: null, range: null },
        { name: "Scimitar", cost: 15, weight: 5, size: "M", type: "S", speed: 5, damage_sm: "1d8", damage_l: "1d8", rof: null, range: null },
        { name: "Short Bow", cost: 30, weight: 2, size: "M", type: "P", speed: 7, damage_sm: "1d6", damage_l: "1d6", rof: 2, range: "50/100/150" },
        { name: "Short Sword", cost: 10, weight: 5, size: "S", type: "P", speed: 3, damage_sm: "1d6", damage_l: "1d8", rof: null, range: null },
        { name: "Sling", cost: 0.2, weight: 0.1, size: "S", type: "B", speed: 6, damage_sm: "1d4+1", damage_l: "1d6+1", rof: 1, range: "40/80/120" },
        { name: "Spear", cost: 1, weight: 5, size: "M", type: "P", speed: 6, damage_sm: "1d6", damage_l: "1d8", rof: 1, range: "20/40/60" },
        { name: "Staff Sling", cost: 0.2, weight: 2, size: "M", type: "B", speed: 11, damage_sm: "1d4+1", damage_l: "1d6+1", rof: 1, range: "30/60/90" },
        { name: "Throwing Knife", cost: 0.5, weight: 0.5, size: "S", type: "P/S", speed: 2, damage_sm: "1d4", damage_l: "1d3", rof: 2, range: "10/20/30" },
        { name: "Two-Handed Sword", cost: 50, weight: 25, size: "L", type: "S", speed: 10, damage_sm: "1d10", damage_l: "3d6", rof: null, range: null },
        { name: "Whip", cost: 1, weight: 2, size: "M", type: "S", speed: 8, damage_sm: "1d2", damage_l: "1d2", rof: null, range: null }
    ],

    armor: [
        { name: "Banded Mail", cost: 400, weight: 35, ac: 4, max_dex: null },
        { name: "Brigandine", cost: 120, weight: 40, ac: 6, max_dex: null },
        { name: "Chain Mail", cost: 75, weight: 40, ac: 5, max_dex: null },
        { name: "Field Plate", cost: 2000, weight: 60, ac: 2, max_dex: null },
        { name: "Full Plate", cost: 4000, weight: 70, ac: 1, max_dex: null },
        { name: "Leather Armor", cost: 5, weight: 15, ac: 8, max_dex: null },
        { name: "Padded Armor", cost: 4, weight: 10, ac: 8, max_dex: null },
        { name: "Plate Mail", cost: 600, weight: 50, ac: 3, max_dex: null },
        { name: "Ring Mail", cost: 100, weight: 40, ac: 7, max_dex: null },
        { name: "Scale Mail", cost: 120, weight: 40, ac: 6, max_dex: null },
        { name: "Shield, Body", cost: 10, weight: 15, ac_bonus: 1, max_dex: null },
        { name: "Shield, Buckler", cost: 1, weight: 3, ac_bonus: 1, max_dex: null },
        { name: "Shield, Medium", cost: 3, weight: 5, ac_bonus: 1, max_dex: null },
        { name: "Shield, Small", cost: 1, weight: 2, ac_bonus: 1, max_dex: null },
        { name: "Splint Mail", cost: 80, weight: 40, ac: 4, max_dex: null },
        { name: "Studded Leather", cost: 20, weight: 25, ac: 7, max_dex: null }
    ],

    gear: [
        { name: "Backpack", cost: 2, weight: 2 },
        { name: "Bedroll", cost: 0.2, weight: 3 },
        { name: "Bell", cost: 1, weight: 0 },
        { name: "Belt Pouch", cost: 1, weight: 0.5 },
        { name: "Block and Tackle", cost: 5, weight: 5 },
        { name: "Candle", cost: 0.01, weight: 0 },
        { name: "Chain (10 ft)", cost: 30, weight: 20 },
        { name: "Chalk", cost: 0.02, weight: 0 },
        { name: "Clothing, Common", cost: 0.5, weight: 3 },
        { name: "Clothing, Fine", cost: 15, weight: 2 },
        { name: "Clothing, Traveler's", cost: 1, weight: 5 },
        { name: "Crowbar", cost: 0.5, weight: 5 },
        { name: "Flask, Empty", cost: 0.03, weight: 0.1 },
        { name: "Flint and Steel", cost: 1, weight: 0 },
        { name: "Grappling Hook", cost: 0.5, weight: 4 },
        { name: "Hammer", cost: 0.5, weight: 2 },
        { name: "Healer's Kit", cost: 5, weight: 1 },
        { name: "Holy Symbol, Wooden", cost: 1, weight: 0 },
        { name: "Holy Symbol, Silver", cost: 25, weight: 1 },
        { name: "Ink", cost: 8, weight: 0 },
        { name: "Ladder (10 ft)", cost: 0.05, weight: 20 },
        { name: "Lantern, Bullseye", cost: 12, weight: 3 },
        { name: "Lantern, Hooded", cost: 7, weight: 2 },
        { name: "Lock, Simple", cost: 5, weight: 1 },
        { name: "Lock, Complex", cost: 100, weight: 2 },
        { name: "Manacles", cost: 15, weight: 2 },
        { name: "Mirror, Small Steel", cost: 10, weight: 0.5 },
        { name: "Oil (1 pint)", cost: 0.5, weight: 1 },
        { name: "Paper (sheet)", cost: 0.2, weight: 0 },
        { name: "Parchment (sheet)", cost: 0.5, weight: 0 },
        { name: "Piton", cost: 0.1, weight: 0.5 },
        { name: "Pole (10 ft)", cost: 0.05, weight: 8 },
        { name: "Pot, Iron", cost: 0.5, weight: 2 },
        { name: "Rations, Dry (1 week)", cost: 5, weight: 10 },
        { name: "Rations, Iron (1 week)", cost: 10, weight: 5 },
        { name: "Rope, Hemp (50 ft)", cost: 1, weight: 10 },
        { name: "Rope, Silk (50 ft)", cost: 10, weight: 5 },
        { name: "Sack, Large", cost: 0.2, weight: 0.5 },
        { name: "Sack, Small", cost: 0.1, weight: 0.3 },
        { name: "Spellbook", cost: 50, weight: 3 },
        { name: "Spike, Iron", cost: 0.1, weight: 0.5 },
        { name: "Tent", cost: 10, weight: 20 },
        { name: "Thieves' Tools", cost: 30, weight: 1 },
        { name: "Torch", cost: 0.01, weight: 1 },
        { name: "Waterskin", cost: 1, weight: 1 },
        { name: "Whetstone", cost: 0.01, weight: 1 },
        { name: "Wineskin", cost: 0.5, weight: 0.5 }
    ],

    weapon_proficiencies: [
        "Battle Axe", "Blowgun", "Bow (Long)", "Bow (Short)", "Club", "Crossbow (Hand)", "Crossbow (Heavy)", "Crossbow (Light)", "Dagger", "Dart", "Flail (Footman's)", "Flail (Horseman's)", "Halberd", "Hammer (Throwing)", "Hammer (War)", "Javelin", "Lance (Heavy)", "Lance (Light)", "Mace (Footman's)", "Mace (Horseman's)", "Morning Star", "Net", "Pick (Heavy)", "Pick (Light)", "Polearm", "Quarterstaff", "Scimitar", "Sling", "Spear", "Staff Sling", "Sword (Bastard)", "Sword (Broad)", "Sword (Long)", "Sword (Short)", "Sword (Two-Handed)", "Trident", "Whip"
    ],

    nonweapon_proficiencies: [
        { name: "Agriculture", ability: "INT", mod: 0 },
        { name: "Animal Handling", ability: "WIS", mod: -1 },
        { name: "Animal Training", ability: "WIS", mod: 0 },
        { name: "Artistic Ability", ability: "WIS", mod: 0 },
        { name: "Blacksmithing", ability: "STR", mod: 0 },
        { name: "Brewing", ability: "INT", mod: 0 },
        { name: "Carpentry", ability: "STR", mod: 0 },
        { name: "Cobbling", ability: "DEX", mod: 0 },
        { name: "Cooking", ability: "INT", mod: 0 },
        { name: "Dancing", ability: "DEX", mod: 0 },
        { name: "Direction Sense", ability: "WIS", mod: +1 },
        { name: "Disguise", ability: "CHA", mod: -1 },
        { name: "Etiquette", ability: "CHA", mod: 0 },
        { name: "Fire-building", ability: "WIS", mod: -1 },
        { name: "Fishing", ability: "WIS", mod: -1 },
        { name: "Forgery", ability: "DEX", mod: -1 },
        { name: "Gaming", ability: "CHA", mod: 0 },
        { name: "Healing", ability: "WIS", mod: -2 },
        { name: "Herbalism", ability: "INT", mod: -2 },
        { name: "Hunting", ability: "WIS", mod: -1 },
        { name: "Languages (Modern)", ability: "INT", mod: 0 },
        { name: "Leatherworking", ability: "INT", mod: 0 },
        { name: "Local History", ability: "CHA", mod: 0 },
        { name: "Mountaineering", ability: "N/A", mod: 0 },
        { name: "Musical Instrument", ability: "DEX", mod: -1 },
        { name: "Navigation", ability: "INT", mod: -2 },
        { name: "Painting", ability: "WIS", mod: 0 },
        { name: "Pottery", ability: "DEX", mod: -2 },
        { name: "Riding (Airborne)", ability: "WIS", mod: -2 },
        { name: "Riding (Land-based)", ability: "WIS", mod: +3 },
        { name: "Rope Use", ability: "DEX", mod: 0 },
        { name: "Seamanship", ability: "DEX", mod: +1 },
        { name: "Sewing", ability: "INT", mod: -1 },
        { name: "Singing", ability: "CHA", mod: 0 },
        { name: "Stonemasonry", ability: "STR", mod: -2 },
        { name: "Swimming", ability: "STR", mod: 0 },
        { name: "Tracking", ability: "WIS", mod: 0 },
        { name: "Weather Sense", ability: "WIS", mod: -1 },
        { name: "Weaving", ability: "INT", mod: -1 }
    ],

    thieving_skills: [
        { name: "Pick Pockets", base: 15 },
        { name: "Open Locks", base: 10 },
        { name: "Find/Remove Traps", base: 5 },
        { name: "Move Silently", base: 10 },
        { name: "Hide in Shadows", base: 5 },
        { name: "Detect Noise", base: 15 },
        { name: "Climb Walls", base: 60 },
        { name: "Read Languages", base: 0 }
    ],

    wizard_spells: [
        { name: "Alarm", level: 1, school: "Abjuration", range: "10 yds", duration: "4 hrs/level", aoe: "20-ft cube", components: "V,S,M", casting_time: "1 rd", save: "None", desc: "Wards an area against intrusion. Alerts caster mentally or audibly when creature larger than a cat enters." },
        { name: "Armor", level: 1, school: "Conjuration", range: "Touch", duration: "Special", aoe: "1 creature", components: "V,S,M", casting_time: "1 rd", save: "None", desc: "Grants AC 6 to unarmored target. Lasts until struck or until 24 hrs pass. Improves with caster level." },
        { name: "Burning Hands", level: 1, school: "Alteration", range: "0", duration: "Instant", aoe: "120-degree arc, 3 ft", components: "V,S", casting_time: "1", save: "Half", desc: "Cone of flame shoots from hands. 1d3+2 damage at 1st level, +2 per additional level." },
        { name: "Charm Person", level: 1, school: "Enchantment", range: "120 yds", duration: "Special", aoe: "1 person", components: "V,S", casting_time: "1", save: "Neg.", desc: "Makes one person regard caster as trusted friend. Save at +1 if threatened. Lasts until dispelled or significant harm occurs." },
        { name: "Comprehend Languages", level: 1, school: "Alteration", range: "Touch", duration: "5 rds/level", aoe: "1 speaking or 1 writing", components: "V,S,M", casting_time: "1 rd", save: "None", desc: "Understands spoken or written language. Does not allow speaking or writing the language." },
        { name: "Dancing Lights", level: 1, school: "Alteration", range: "40 yds+10/level", duration: "2 rds/level", aoe: "Special", components: "V,S,M", casting_time: "1", save: "None", desc: "Creates 1-4 torch-sized lights, 1 glowing sphere, or faintly glowing humanoid figure. Moves as caster directs." },
        { name: "Detect Magic", level: 1, school: "Divination", range: "0", duration: "2 rds/level", aoe: "10x60 ft", components: "V,S", casting_time: "1", save: "None", desc: "Detects magical radiations in a path 10 ft wide and up to 60 ft long. Identifies intensity." },
        { name: "Enlarge", level: 1, school: "Alteration", range: "5 yds/level", duration: "5 rds/level", aoe: "1 creature or obj", components: "V,S,M", casting_time: "1", save: "Neg.", desc: "Increases size by 25% per caster level (max 200%). Doubles weight. +1 damage per 25% growth." },
        { name: "Erase", level: 1, school: "Alteration", range: "30 yds", duration: "Instant", aoe: "1 object or page/level", components: "V,S,M", casting_time: "1 rd", save: "Neg.", desc: "Removes magical or mundane writing from a scroll or 1-2 pages. Cannot remove spellbooks or protection." },
        { name: "Feather Fall", level: 1, school: "Alteration", range: "10 yds/level", duration: "1 rd/level", aoe: "Special", components: "V,M", casting_time: "Special", save: "None", desc: "Objects or creatures fall slowly. Affects 1 creature or object per level. Caster can interrupt normal spell to cast this." },
        { name: "Find Familiar", level: 1, school: "Conjuration", range: "1 mile/level", duration: "Special", aoe: "1 familiar", components: "V,S,M", casting_time: "2-12 hrs", save: "None", desc: "Summons a magical animal companion. Grants empathic link, sensory sharing, and HP bonus. If familiar dies, caster loses 1d4x10% HP permanently." },
        { name: "Friends", level: 1, school: "Enchantment", range: "0", duration: "1d4 rds+1 rd/level", aoe: "10-ft radius", components: "V,S,M", casting_time: "1", save: "Special", desc: "Caster appears more charismatic. +2d4 CHA bonus. When spell ends, creatures make reaction check at -2 penalty." },
        { name: "Grease", level: 1, school: "Conjuration", range: "10 yds", duration: "3 rds+1 rd/level", aoe: "10x10 ft", components: "V,S,M", casting_time: "1", save: "Special", desc: "Covers area with slippery grease. Creatures must save or fall. Items dropped must save or be dropped." },
        { name: "Hold Portal", level: 1, school: "Alteration", range: "20 yds/level", duration: "1 rd/level", aoe: "20 sq ft/level", components: "V", casting_time: "1", save: "None", desc: "Magically holds a door, gate, or portal shut. Can be forced by knock spell or by creatures with 4+1 HD or 18+ STR." },
        { name: "Identify", level: 1, school: "Divination", range: "0", duration: "1 rd/level", aoe: "1 item/level", components: "V,S,M", casting_time: "Special", save: "None", desc: "Reveals magical properties of one item per level. 100 gp pearl consumed. Caster ages 1 year." },
        { name: "Jump", level: 1, school: "Alteration", range: "Touch", duration: "1d3 rds+1 rd/level", aoe: "1 creature", components: "V,S,M", casting_time: "1", save: "None", desc: "Creature can leap 30 ft forward or 10 ft backward or upward. One jump per round." },
        { name: "Light", level: 1, school: "Alteration", range: "60 yds", duration: "1 hr+1 turn/level", aoe: "20-ft radius", components: "V,M", casting_time: "1", save: "Special", desc: "Creates light as bright as full daylight in 20-ft radius. Can be cast on object or creature's eyes (blinding, save negates)." },
        { name: "Magic Missile", level: 1, school: "Evocation", range: "60 yds+10/level", duration: "Instant", aoe: "1-5 creatures", components: "V,S", casting_time: "1", save: "None", desc: "Creates 1 missile at 1st level, +2 at 3rd, +3 at 5th, +4 at 7th, +5 at 9th. Each missile does 1d4+1 damage and always hits." },
        { name: "Mending", level: 1, school: "Alteration", range: "30 yds", duration: "Permanent", aoe: "1 object", components: "V,S,M", casting_time: "1", save: "None", desc: "Repairs small breaks or tears in objects. Can repair one break per caster level. Cannot repair magic items." },
        { name: "Message", level: 1, school: "Alteration", range: "0", duration: "5 rds/level", aoe: "Special", components: "V,S,M", casting_time: "1", save: "None", desc: "Whispered message travels to designated recipient who can whisper back. Can pass through barriers." },
        { name: "Mount", level: 1, school: "Conjuration", range: "10 yds/level", duration: "2 hrs+1 hr/level", aoe: "1 mount", components: "V,S,M", casting_time: "1 turn", save: "None", desc: "Summons a riding horse or pony with saddle and tack. Cannot attack. Disappears if reduced to 0 HP." },
        { name: "Protection from Evil", level: 1, school: "Abjuration", range: "Touch", duration: "2 rds/level", aoe: "1 creature", components: "V,S,M", casting_time: "1", save: "None", desc: "+2 AC and saves vs evil creatures. Evil summoned creatures cannot touch protected creature. Prevents mental control." },
        { name: "Read Magic", level: 1, school: "Divination", range: "0", duration: "2 rds/level", aoe: "Special", components: "V,S,M", casting_time: "1 rd", save: "None", desc: "Allows caster to read magical inscriptions on items, books, scrolls. Does not decode ciphers or unknown languages." },
        { name: "Shield", level: 1, school: "Evocation", range: "0", duration: "5 rds/level", aoe: "Special", components: "V,S", casting_time: "1", save: "None", desc: "Invisible barrier gives AC 2 vs missiles, AC 4 vs other attacks. Blocks magic missile." },
        { name: "Shocking Grasp", level: 1, school: "Alteration", range: "Touch", duration: "Special", aoe: "1 creature", components: "V,S", casting_time: "1", save: "None", desc: "Delivers 1d8+1 electrical damage per caster level (max 5d8). Must touch target. +3 bonus to hit metal armor." },
        { name: "Sleep", level: 1, school: "Enchantment", range: "30 yds", duration: "5 rds/level", aoe: "Special", components: "V,S,M", casting_time: "1", save: "None", desc: "Puts 2d4 HD of creatures to sleep (max 4+1 HD). Weakest creatures affected first. No save. Slapping or wounding wakes them." },
        { name: "Spider Climb", level: 1, school: "Alteration", range: "Touch", duration: "1 rd+1 rd/level", aoe: "1 creature", components: "V,S,M", casting_time: "1", save: "None", desc: "Creature can climb walls and ceilings like a spider. Movement rate 6. Cannot be dislodged." },
        { name: "Taunt", level: 1, school: "Enchantment", range: "60 yds", duration: "1 rd", aoe: "15-ft radius", components: "V,S,M", casting_time: "1", save: "Neg.", desc: "Creatures in area must save or attack caster with melee weapons if possible. Spellcasters lose 1 round of casting." },
        { name: "Tenser's Floating Disc", level: 1, school: "Evocation", range: "20 yds", duration: "3 turns+1 turn/level", aoe: "3-ft diameter disc", components: "V,S,M", casting_time: "1", save: "None", desc: "Creates floating disc that follows caster, carrying up to 100 lbs per level. Moves 6 per round." },
        { name: "Unseen Servant", level: 1, school: "Conjuration", range: "0", duration: "1 hr+1 turn/level", aoe: "30-ft radius", components: "V,S,M", casting_time: "1", save: "None", desc: "Invisible force obeys caster's commands. Can lift 20 lbs, open doors, draw curtains. Cannot attack." },
        { name: "Ventriloquism", level: 1, school: "Illusion", range: "10 yds/level", duration: "4 rds+1 rd/level", aoe: "1 object or creature", components: "V,M", casting_time: "1", save: "Neg.", desc: "Caster can make voice appear to come from another location. Save to detect if viewer suspects." },
        { name: "Wall of Fog", level: 1, school: "Evocation", range: "30 yds", duration: "2d4 rds+1 rd/level", aoe: "20x10x10 ft", components: "V,S,M", casting_time: "1", save: "None", desc: "Creates opaque wall of fog. Vision beyond is blocked. Strong wind disperses in 1 round." },
        { name: "Wizard Mark", level: 1, school: "Alteration", range: "Touch", duration: "Permanent", aoe: "1 object", components: "V,S,M", casting_time: "1", save: "None", desc: "Inscribes personal rune on object. Can be visible or invisible. Detectable by detect magic." },
        { name: "Alter Self", level: 2, school: "Alteration", range: "0", duration: "3d4 rds+2 rds/level", aoe: "The caster", components: "V,S", casting_time: "2", save: "None", desc: "Caster can change appearance including height, weight, facial features, skin color. Cannot duplicate specific person perfectly." },
        { name: "Bind", level: 2, school: "Enchantment", range: "30 yds", duration: "1 rd/level", aoe: "50-ft rope", components: "V,S,M", casting_time: "2", save: "Neg.", desc: "Causes rope to move and entangle target. Target must save or be bound. Rope has AC 6 and 4 HP." },
        { name: "Blur", level: 2, school: "Illusion", range: "0", duration: "3 rds+1 rd/level", aoe: "The caster", components: "V,M", casting_time: "2", save: "None", desc: "Caster's outline becomes blurred. All attacks suffer -4 penalty. Does not work against creatures that don't rely on sight." },
        { name: "Continual Light", level: 2, school: "Alteration", range: "60 yds", duration: "Permanent", aoe: "60-ft radius", components: "V,S", casting_time: "2", save: "Special", desc: "Creates permanent light as bright as full daylight. Can be cast on object or creature's eyes (save negates, -4 penalty)." },
        { name: "Darkness, 15' Radius", level: 2, school: "Alteration", range: "10 yds/level", duration: "1 turn+1 rd/level", aoe: "15-ft radius", components: "V,S,M", casting_time: "2", save: "None", desc: "Creates globe of impenetrable darkness. Normal and magical light cannot illuminate it. Infravision and ultravision useless." },
        { name: "Detect Evil", level: 2, school: "Divination", range: "0", duration: "5 rds/level", aoe: "10x60 ft", components: "V,S", casting_time: "2", save: "None", desc: "Detects evil intent or evil enchanted objects. Does not detect traps, poison, or neutral creatures." },
        { name: "Detect Invisibility", level: 2, school: "Divination", range: "0", duration: "5 rds/level", aoe: "10x60 ft", components: "V,S,M", casting_time: "2", save: "None", desc: "Detects invisible creatures and objects. Also reveals astral and ethereal creatures." },
        { name: "ESP", level: 2, school: "Divination", range: "0", duration: "1 rd/level", aoe: "5 yds/level", components: "V,S,M", casting_time: "2", save: "None", desc: "Caster can detect surface thoughts of any creatures in range. Blocked by 2 ft of stone, 2 inches of metal, or thin sheet of lead." },
        { name: "Flaming Sphere", level: 2, school: "Evocation", range: "10 yds", duration: "1 rd/level", aoe: "5-ft diameter", components: "V,S,M", casting_time: "2", save: "Neg.", desc: "Creates rolling ball of fire. Moves 30 ft per round. Creatures in path take 2d4 damage (save for half)." },
        { name: "Fog Cloud", level: 2, school: "Alteration", range: "10 yds", duration: "4 rds+1 rd/level", aoe: "40x20x20 ft", components: "V,S", casting_time: "2", save: "None", desc: "Creates dense fog. Visibility reduced to 2d4 ft. Strong wind disperses in 4 rounds." },
        { name: "Fools' Gold", level: 2, school: "Illusion", range: "10 yds", duration: "1 hr/level", aoe: "10 coins/level", components: "V,S,M", casting_time: "1 rd", save: "Special", desc: "Copper coins appear to be gold. Detect magic reveals illusion. True seeing or touch by creature with 18+ INT reveals truth." },
        { name: "Forget", level: 2, school: "Enchantment", range: "30 yds", duration: "Permanent", aoe: "1-4 creatures", components: "V,S", casting_time: "2", save: "Neg.", desc: "Causes creatures to forget last 1d6+2 rounds. Can erase specific memories if caster knows them." },
        { name: "Invisibility", level: 2, school: "Illusion", range: "Touch", duration: "Special", aoe: "1 creature or object", components: "V,S,M", casting_time: "2", save: "None", desc: "Target becomes invisible. Ends if target attacks or casts a spell. Otherwise lasts 24 hours." },
        { name: "Knock", level: 2, school: "Alteration", range: "60 yds", duration: "Instant", aoe: "10 sq ft/level", components: "V", casting_time: "1", save: "None", desc: "Opens stuck, barred, locked, or wizard-locked doors. Also opens secret doors. Does not remove traps." },
        { name: "Leomund's Trap", level: 2, school: "Illusion", range: "Touch", duration: "Permanent", aoe: "1 object", components: "V,S,M", casting_time: "1 rd", save: "None", desc: "Makes object appear trapped to detect magic and find traps. Does not actually trap object." },
        { name: "Levitate", level: 2, school: "Alteration", range: "20 yds/level", duration: "1 turn/level", aoe: "1 creature or object", components: "V,S,M", casting_time: "2", save: "Neg.", desc: "Target can move up or down at 20 ft per round. Cannot move horizontally. Caster can levitate self." },
        { name: "Magic Mouth", level: 2, school: "Alteration", range: "Touch", duration: "Until discharged", aoe: "1 object", components: "V,S,M", casting_time: "2", save: "None", desc: "Imbues object with enchanted mouth that speaks message when triggered by specified event." },
        { name: "Mirror Image", level: 2, school: "Illusion", range: "0", duration: "3 rds/level", aoe: "6-ft radius", components: "V,S", casting_time: "2", save: "None", desc: "Creates 1d4+1 illusory duplicates of caster. When attacked, roll to see if duplicate is hit. Disappears when struck." },
        { name: "Pyrotechnics", level: 2, school: "Alteration", range: "120 yds", duration: "Special", aoe: "1 fire source", components: "V,S,M", casting_time: "2", save: "None", desc: "Turns fire into fireworks (blinding within 120 ft for 1d4+1 rds) or choking smoke (20x20x20 ft, -2 attacks, -2 STR/DEX)." },
        { name: "Ray of Enfeeblement", level: 2, school: "Enchantment", range: "10 yds+5/level", duration: "1 rd/level", aoe: "1 creature", components: "V,S", casting_time: "2", save: "Neg.", desc: "Black ray reduces target's STR by 25%+2% per level (max 50%). If STR drops below 5, target cannot move." },
        { name: "Rope Trick", level: 2, school: "Alteration", range: "Touch", duration: "2 turns/level", aoe: "1 rope", components: "V,S,M", casting_time: "2", save: "None", desc: "Top 5 ft of rope becomes invisible and opens to extradimensional space. Up to 6 Medium creatures can hide inside." },
        { name: "Scare", level: 2, school: "Enchantment", range: "30 yds", duration: "1d4 rds+1 rd/level", aoe: "15-ft radius", components: "V,S,M", casting_time: "2", save: "Special", desc: "Creatures with less than 6 HD flee in panic for duration. Creatures with 6+ HD save at +4." },
        { name: "Shatter", level: 2, school: "Alteration", range: "60 yds", duration: "Instant", aoe: "3-ft radius", components: "V,S,M", casting_time: "2", save: "Neg.", desc: "Vibrations shatter brittle objects (crystal, glass, ceramic). Also damages crystalline creatures (6d6, save for half)." },
        { name: "Stinking Cloud", level: 2, school: "Evocation", range: "30 yds", duration: "1 rd/level", aoe: "20x20x20 ft", components: "V,S,M", casting_time: "2", save: "Special", desc: "Nauseating vapors cause creatures to retch helplessly for 2d4 rounds (save negates). Those who save are -2 attacks while in cloud." },
        { name: "Strength", level: 2, school: "Alteration", range: "Touch", duration: "1 hr/level", aoe: "1 creature", components: "V,S,M", casting_time: "1 turn", save: "None", desc: "Increases target's STR. Warriors gain 1d8, priests 1d6, rogues 1d6, wizards 1d4. Cannot exceed 18/00." },
        { name: "Web", level: 2, school: "Evocation", range: "5 yds/level", duration: "2 turns/level", aoe: "8,000 cu ft", components: "V,S,M", casting_time: "2", save: "Neg.", desc: "Creates sticky strands. Creatures caught must save or be stuck. STR 18 breaks free in 2 rounds. Fire burns web in 2 rounds, causing 2d4 damage." },
        { name: "Wizard Lock", level: 2, school: "Alteration", range: "Touch", duration: "Permanent", aoe: "30 sq ft/level", components: "V,S", casting_time: "2", save: "None", desc: "Magically locks door, chest, or portal. Can be opened by caster, knock spell, or creatures with 4+1 HD or 18+ STR." },
        { name: "Blink", level: 3, school: "Alteration", range: "0", duration: "1 rd/level", aoe: "The caster", components: "V,S", casting_time: "1", save: "None", desc: "Caster randomly shifts between Material and Ethereal Plane. 25% chance attacker misses entirely. Caster can attack while blinking." },
        { name: "Clairaudience", level: 3, school: "Divination", range: "Special", duration: "1 rd/level", aoe: "The caster", components: "V,S,M", casting_time: "3", save: "None", desc: "Caster can hear at a distant location as if physically present. Range 1 mile. Must know location or have seen it." },
        { name: "Clairvoyance", level: 3, school: "Divination", range: "Special", duration: "1 rd/level", aoe: "The caster", components: "V,S,M", casting_time: "3", save: "None", desc: "Caster can see at a distant location as if physically present. Range 1 mile. Must know location or have seen it." },
        { name: "Dispel Magic", level: 3, school: "Abjuration", range: "120 yds", duration: "Instant", aoe: "30-ft cube", components: "V,S", casting_time: "3", save: "None", desc: "Ends magical spells and effects. Caster level check vs spell level to dispel. Area dispel affects all spells in area." },
        { name: "Explosive Runes", level: 3, school: "Alteration", range: "Touch", duration: "Until discharged", aoe: "1 object", components: "V,S", casting_time: "3", save: "Half", desc: "Runes explode when read, dealing 6d6+6 damage to reader (save for half). Also damages creatures within 10 ft (save for half)." },
        { name: "Fireball", level: 3, school: "Evocation", range: "10 yds+10/level", duration: "Instant", aoe: "20-ft radius", components: "V,S,M", casting_time: "3", save: "Half", desc: "Massive explosion of flame. 1d6 damage per caster level (max 10d6). Flammable materials ignite. Save for half damage." },
        { name: "Flame Arrow", level: 3, school: "Conjuration", range: "30 yds", duration: "1 rd", aoe: "Special", components: "V,S,M", casting_time: "3", save: "None", desc: "Transforms arrows or bolts into fiery projectiles. +1 damage per missile. Can ignite flammable materials." },
        { name: "Fly", level: 3, school: "Alteration", range: "Touch", duration: "1 turn+1 rd/level", aoe: "1 creature", components: "V,S,M", casting_time: "3", save: "None", desc: "Target can fly at 12 (MC: B). Can carry normal gear. Spell ends if target strikes ceiling or wall while flying." },
        { name: "Gust of Wind", level: 3, school: "Alteration", range: "0", duration: "1 rd", aoe: "10-ft wide, 10 yds/level long", components: "V,S,M", casting_time: "3", save: "None", desc: "Strong wind blows in direction caster faces. Knocks over small flying creatures, extinguishes candles/torches, fans fires." },
        { name: "Haste", level: 3, school: "Alteration", range: "60 yds", duration: "1 rd/level", aoe: "40x40 ft", components: "V,S,M", casting_time: "3", save: "None", desc: "Up to 24 creatures in area move and attack at double normal rate. Spell ends, creatures are slowed for equal duration. Ages targets 1 year." },
        { name: "Hold Person", level: 3, school: "Enchantment", range: "120 yds", duration: "2 rds/level", aoe: "1-3 creatures", components: "V", casting_time: "3", save: "Neg.", desc: "Paralyzes 1-3 humanoid creatures. Save negates. Target is aware but cannot move or speak." },
        { name: "Invisibility, 10' Radius", level: 3, school: "Illusion", range: "Touch", duration: "Special", aoe: "10-ft radius", components: "V,S,M", casting_time: "3", save: "None", desc: "All creatures within 10 ft of target become invisible. Ends for any creature that attacks or casts a spell." },
        { name: "Item", level: 3, school: "Alteration", range: "Touch", duration: "4 hrs/level", aoe: "1 object", components: "V,S", casting_time: "3", save: "None", desc: "Shrinks one nonmagical object to 1/12 size. Weight reduced to 1/8. Can be reversed to restore." },
        { name: "Lightning Bolt", level: 3, school: "Evocation", range: "40 yds+10/level", duration: "Instant", aoe: "5 ft wide, 40 yds+5/level long", components: "V,S,M", casting_time: "3", save: "Half", desc: "Stroke of lightning. 1d6 damage per caster level (max 10d6). Bounces off walls. Save for half damage." },
        { name: "Monster Summoning I", level: 3, school: "Conjuration", range: "Special", duration: "2 rds+1 rd/level", aoe: "Special", components: "V,S,M", casting_time: "3", save: "None", desc: "Summons 2d4 1st-level monsters to fight for caster. Appear within 30 yds. Obey caster's commands." },
        { name: "Phantom Steed", level: 3, school: "Illusion", range: "Touch", duration: "1 hr/level", aoe: "1 mount", components: "V,S", casting_time: "1 turn", save: "None", desc: "Creates quasi-real horse-like creature. AC 2, 10 HP, MV 24. Cannot fight. Only caster can ride." },
        { name: "Protection from Evil, 10' Radius", level: 3, school: "Abjuration", range: "Touch", duration: "2 rds/level", aoe: "10-ft radius", components: "V,S,M", casting_time: "3", save: "None", desc: "All within 10 ft of target gain +2 AC and saves vs evil. Evil summoned creatures cannot touch anyone in area." },
        { name: "Protection from Normal Missiles", level: 3, school: "Abjuration", range: "Touch", duration: "1 turn/level", aoe: "1 creature", components: "V,S,M", casting_time: "3", save: "None", desc: "Target is immune to normal missiles (arrows, bolts, stones). Magic missiles and large missiles (boulders) still hit." },
        { name: "Slow", level: 3, school: "Alteration", range: "90 yds+10/level", duration: "1 rd/level", aoe: "40x40 ft", components: "V,S,M", casting_time: "3", save: "Neg.", desc: "Up to 24 creatures move and attack at half rate. -4 AC penalty. Spellcasting takes 2 rounds." },
        { name: "Suggestion", level: 3, school: "Enchantment", range: "30 yds", duration: "1 hr+1 hr/level", aoe: "1 creature", components: "V,M", casting_time: "3", save: "Neg.", desc: "Target must follow reasonable suggestion. Unreasonable suggestions give +1 to +4 save bonus. Cannot suggest suicide." },
        { name: "Tongues", level: 3, school: "Alteration", range: "0", duration: "1 rd/level", aoe: "30-ft radius", components: "V,M", casting_time: "3", save: "None", desc: "Caster can speak and understand any language. Others in area can understand caster. Does not read/write." },
        { name: "Vampiric Touch", level: 3, school: "Necromancy", range: "Touch", duration: "Instant", aoe: "1 creature", components: "V,S", casting_time: "3", save: "None", desc: "Touch drains 1d6 HP per 2 caster levels from target. Caster gains temporary HP equal to damage dealt. Cannot exceed normal max HP." },
        { name: "Water Breathing", level: 3, school: "Alteration", range: "Touch", duration: "1 hr/level", aoe: "1 creature", components: "V,S,M", casting_time: "3", save: "None", desc: "Target can breathe underwater. Can be reversed to allow water-breathing creatures to breathe air." },
        { name: "Wind Wall", level: 3, school: "Alteration", range: "10 yds/level", duration: "1 rd/level", aoe: "10x5 yds/level x 2 yds", components: "V,S,M", casting_time: "3", save: "None", desc: "Vertical curtain of strong wind. Arrows and bolts are deflected. Gases and small flying creatures cannot pass." }
    ],

    priest_spells: [
        { name: "Bless", level: 1, sphere: "All", range: "60 yds", duration: "6 rds", aoe: "50-ft cube", components: "V,S,M", casting_time: "1 rd", save: "None", desc: "Allies gain +1 to hit and +1 save vs fear. Opposite of curse." },
        { name: "Command", level: 1, sphere: "Charm", range: "30 yds", duration: "1 rd", aoe: "1 creature", components: "V", casting_time: "1", save: "Neg.", desc: "One-word command that target obeys for 1 round. 'Die' makes target fall unconscious for 1 round (save negates)." },
        { name: "Cure Light Wounds", level: 1, sphere: "Healing", range: "Touch", duration: "Permanent", aoe: "1 creature", components: "V,S", casting_time: "5", save: "None", desc: "Heals 1d8 HP. Cannot raise above maximum. Reversed (cause light wounds) inflicts 1d8 damage." },
        { name: "Detect Evil", level: 1, sphere: "All", range: "0", duration: "1 turn+1 rd/level", aoe: "10x120 ft", components: "V,S", casting_time: "1 rd", save: "None", desc: "Detects evil intent or evil enchanted objects. Does not detect traps, poison, or neutral creatures." },
        { name: "Detect Magic", level: 1, sphere: "Divination", range: "0", duration: "1 turn+1 rd/level", aoe: "10x30 yds", components: "V,S,M", casting_time: "1 rd", save: "None", desc: "Detects magical auras. Identifies intensity (dim, faint, moderate, strong, overwhelming)." },
        { name: "Entangle", level: 1, sphere: "Plant", range: "80 yds", duration: "1 turn", aoe: "40-ft cube", components: "V,S,M", casting_time: "4", save: "Neg.", desc: "Plants grow and entangle creatures in area. Creatures must save or be held for 1d3 rounds." },
        { name: "Faerie Fire", level: 1, sphere: "Weather", range: "80 yds", duration: "4 rds/level", aoe: "8 creatures", components: "V,M", casting_time: "4", save: "None", desc: "Outlines creatures/objects with pale glow. -2 AC penalty. Does not affect infravision." },
        { name: "Invisibility to Animals", level: 1, sphere: "Animal", range: "Touch", duration: "1 turn+1 rd/level", aoe: "1 creature/level", components: "S,M", casting_time: "4", save: "None", desc: "Animals cannot see, hear, or smell target(s). Does not work on magical beasts or intelligent animals." },
        { name: "Light", level: 1, sphere: "Sun", range: "120 yds", duration: "1 hr+1 turn/level", aoe: "20-ft radius", components: "V,S", casting_time: "4", save: "Special", desc: "Creates light as bright as full daylight. Can be cast on object or creature's eyes (save negates)." },
        { name: "Magic Stone", level: 1, sphere: "Combat", range: "Touch", duration: "Special", aoe: "3 pebbles", components: "V,S,M", casting_time: "1", save: "None", desc: "Three stones become magical missiles. +1 to hit, 1d6+1 damage vs undead. Each stone is good for one hit." },
        { name: "Protection from Evil", level: 1, sphere: "Protection", range: "Touch", duration: "3 rds/level", aoe: "1 creature", components: "V,S,M", casting_time: "4", save: "None", desc: "+2 AC and saves vs evil creatures. Evil summoned creatures cannot touch protected creature." },
        { name: "Remove Fear", level: 1, sphere: "Charm", range: "Touch", duration: "1 hr", aoe: "1 creature", components: "V,S", casting_time: "1", save: "Special", desc: "+4 save vs fear for 1 hour. If cast on frightened creature, save to negate fear. Reversed causes fear." },
        { name: "Sanctuary", level: 1, sphere: "Protection", range: "Touch", duration: "2 rds+1 rd/level", aoe: "1 creature", components: "V,S,M", casting_time: "4", save: "None", desc: "Opponents must save vs spell to attack protected creature. If save fails, they must attack someone else. Ends if protected creature attacks." },
        { name: "Shillelagh", level: 1, sphere: "Plant", range: "Touch", duration: "4 rds+1 rd/level", aoe: "1 club or quarterstaff", components: "V,S,M", casting_time: "2", save: "None", desc: "Club or quarterstaff becomes +1 weapon. Damage becomes 2d4. Only caster can wield effectively." },
        { name: "Aid", level: 2, sphere: "Necromantic", range: "Touch", duration: "1 rd+1 rd/level", aoe: "1 creature", components: "V,S,M", casting_time: "5", save: "None", desc: "Target gains 1d8 temporary HP, +1 THAC0, and +1 save vs fear. Temporary HP are lost first." },
        { name: "Augury", level: 2, sphere: "Divination", range: "0", duration: "Special", aoe: "The caster", components: "V,S,M", casting_time: "2 rds", save: "None", desc: "Learns whether a proposed action will be weal (good), woe (bad), both, or neither. 70%+1% per level accuracy." },
        { name: "Barkskin", level: 2, sphere: "Plant", range: "Touch", duration: "4 rds+1 rd/level", aoe: "1 creature", components: "V,S,M", casting_time: "5", save: "None", desc: "Target's skin becomes tough like bark. AC becomes 6 (or improves by 1 if already better). +1 save vs attacks." },
        { name: "Charm Person or Mammal", level: 2, sphere: "Animal", range: "80 yds", duration: "Special", aoe: "1 person or mammal", components: "V,S", casting_time: "5", save: "Neg.", desc: "Makes one person or mammal regard caster as trusted friend. Mammals get -1 save. Lasts until dispelled or harm occurs." },
        { name: "Cure Moderate Wounds", level: 2, sphere: "Healing", range: "Touch", duration: "Permanent", aoe: "1 creature", components: "V,S", casting_time: "5", save: "None", desc: "Heals 2d4+2 HP. Cannot raise above maximum. Reversed (cause moderate wounds) inflicts 2d4+2 damage." },
        { name: "Find Traps", level: 2, sphere: "Divination", range: "0", duration: "3 turns", aoe: "10x30 ft", components: "V,S", casting_time: "5", save: "None", desc: "Caster can detect traps as thief of same level. Only detects mechanical traps, not magical ones." },
        { name: "Hold Person", level: 2, sphere: "Charm", range: "120 yds", duration: "2 rds/level", aoe: "1-3 creatures", components: "V,S,M", casting_time: "5", save: "Neg.", desc: "Paralyzes 1-3 humanoid creatures. Save negates. Target is aware but cannot move or speak." },
        { name: "Resist Fire/Resist Cold", level: 2, sphere: "Protection", range: "Touch", duration: "1 turn/level", aoe: "1 creature", components: "V,S,M", casting_time: "5", save: "None", desc: "Target takes half damage from fire or cold. If save is normally allowed, target takes quarter damage on successful save." },
        { name: "Silence, 15' Radius", level: 2, sphere: "Guardian", range: "120 yds", duration: "2 rds/level", aoe: "15-ft radius", components: "V,S", casting_time: "5", save: "None", desc: "No sound can enter or leave area. Prevents spellcasting with verbal components. Can be cast on creature (save negates)." },
        { name: "Slow Poison", level: 2, sphere: "Healing", range: "Touch", duration: "1 hr/level", aoe: "1 creature", components: "V,S,M", casting_time: "1", save: "None", desc: "Poison in target's system is neutralized for duration. Target takes no damage from poison during this time." },
        { name: "Snake Charm", level: 2, sphere: "Animal", range: "30 yds", duration: "Special", aoe: "30-ft radius", components: "V,S", casting_time: "5", save: "None", desc: "Charms HD of snakes equal to caster's level. Snakes become torpid and harmless for duration." },
        { name: "Spiritual Hammer", level: 2, sphere: "Combat", range: "10 yds/level", duration: "1 rd/level", aoe: "Special", components: "V,S,M", casting_time: "5", save: "None", desc: "Creates force hammer that attacks at caster's THAC0. +1 damage per 3 levels. Returns to caster after each attack." },
        { name: "Trip", level: 2, sphere: "Plant", range: "Touch", duration: "1 turn/level", aoe: "1 object", components: "V,S,M", casting_time: "4", save: "Neg.", desc: "Vine or rope trips creatures passing through. Creatures up to 400 lbs are tripped (save negates)." },
        { name: "Warp Wood", level: 2, sphere: "Plant", range: "10 yds/level", duration: "Permanent", aoe: "Special", components: "V,S", casting_time: "5", save: "None", desc: "Bends wooden items. Can affect one item per caster level. Can warp doors shut, ruin bows, etc." },
        { name: "Withdraw", level: 2, sphere: "Protection", range: "0", duration: "2 rds/level", aoe: "The caster", components: "V,S,M", casting_time: "5", save: "None", desc: "Caster can sense attacks 1 round in advance. +4 AC and saves. Cannot attack while spell is active." },
        { name: "Wyvern Watch", level: 2, sphere: "Guardian", range: "30 yds", duration: "8 hrs or until triggered", aoe: "5-ft radius", components: "V,S,M", casting_time: "1 rd", save: "Neg.", desc: "Creates spectral wyvern that guards area. If creature enters, wyvern strikes (save or paralyzed for 1d6+2 rounds)." },
        { name: "Animate Dead", level: 3, sphere: "Necromantic", range: "10 yds", duration: "Permanent", aoe: "Special", components: "V,S,M", casting_time: "1 rd", save: "None", desc: "Creates skeletons or zombies from dead bodies. Creates 1 per 2 caster levels. Controlled by caster." },
        { name: "Call Lightning", level: 3, sphere: "Weather", range: "0", duration: "1 turn/level", aoe: "360-ft radius", components: "V,S", casting_time: "1 turn", save: "Half", desc: "Caster can call lightning bolts from storm clouds. 1 bolt per turn, 2d8 damage (save for half). Must be outdoors in storm." },
        { name: "Continual Light", level: 3, sphere: "Sun", range: "120 yds", duration: "Permanent", aoe: "60-ft radius", components: "V,S", casting_time: "6", save: "Special", desc: "Creates permanent light as bright as full daylight. Can be cast on object or creature's eyes (save negates, -4 penalty)." },
        { name: "Cure Disease", level: 3, sphere: "Healing", range: "Touch", duration: "Permanent", aoe: "1 creature", components: "V,S", casting_time: "1 turn", save: "None", desc: "Cures one disease. Also kills parasites (green slime, rot grubs, etc.). Reversed (cause disease) infects target." },
        { name: "Dispel Magic", level: 3, sphere: "Protection", range: "60 yds", duration: "Instant", aoe: "30-ft cube", components: "V,S", casting_time: "6", save: "None", desc: "Ends magical spells and effects. Caster level check vs spell level to dispel. Area dispel affects all spells in area." },
        { name: "Feign Death", level: 3, sphere: "Necromantic", range: "Touch", duration: "1 hr+1 turn/level", aoe: "1 creature", components: "V,S,M", casting_time: "1 rd", save: "None", desc: "Target appears dead but is actually in cataleptic state. Cannot be harmed by poison, paralysis, or disease. Needs only 1/10 normal air." },
        { name: "Glyph of Warding", level: 3, sphere: "Guardian", range: "Touch", duration: "Until triggered", aoe: "Special", components: "V,S,M", casting_time: "Special", save: "Special", desc: "Inscription that harms intruders. Can deal 1d4 per caster level damage (max 10d4) or other effects. Save for half damage." },
        { name: "Locate Object", level: 3, sphere: "Divination", range: "0", duration: "1 rd/level", aoe: "Special", components: "V,S,M", casting_time: "1 turn", save: "None", desc: "Caster can sense direction to known object or type of object within 60 yds. Blocked by lead." },
        { name: "Magic Vestment", level: 3, sphere: "Protection", range: "Touch", duration: "4 rds/level", aoe: "1 garment", components: "V,S,M", casting_time: "1 rd", save: "None", desc: "Enchanted garment becomes +1 armor. +1 per 4 caster levels (max +4). Only works for priest's alignment." },
        { name: "Meld into Stone", level: 3, sphere: "Elemental (Earth)", range: "Touch", duration: "8 hrs", aoe: "The caster", components: "V,S,M", casting_time: "5", save: "None", desc: "Caster and up to 100 lbs of gear merge into stone. Can see out but cannot be seen. Can hear but not speak." },
        { name: "Negative Plane Protection", level: 3, sphere: "Protection", range: "Touch", duration: "Special", aoe: "1 creature", components: "V,S", casting_time: "1 rd", save: "None", desc: "Protects from energy drain attacks. Negates first 1d4+2 energy drain levels. Then spell ends." },
        { name: "Plant Growth", level: 3, sphere: "Plant", range: "160 yds", duration: "Permanent", aoe: "Special", components: "V,S", casting_time: "1 rd", save: "None", desc: "Causes plants to grow rapidly. Overgrowth version makes area impassable. Enrichment version increases crop yield 50%." },
        { name: "Prayer", level: 3, sphere: "Combat", range: "0", duration: "1 rd/level", aoe: "60-ft radius", components: "V,S,M", casting_time: "6", save: "None", desc: "Allies gain +1 to hit, damage, and saves. Enemies suffer -1 penalty. Does not stack with bless." },
        { name: "Protection from Fire", level: 3, sphere: "Protection", range: "Touch", duration: "Special", aoe: "1 creature", components: "V,S", casting_time: "6", save: "None", desc: "Absorbs 12 HP per caster level of fire damage. Then spell ends. Can be cast as immediate protection (absorbs half damage until expended)." },
        { name: "Remove Curse", level: 3, sphere: "Protection", range: "Touch", duration: "Permanent", aoe: "Special", components: "V,S", casting_time: "6", save: "None", desc: "Removes one curse from creature or item. Does not remove curse from cursed magic items (merely allows removal). Reversed bestows curse." },
        { name: "Remove Paralysis", level: 3, sphere: "Protection", range: "10 yds/level", duration: "Permanent", aoe: "1-4 creatures", components: "V,S", casting_time: "6", save: "None", desc: "Removes paralysis from 1-4 creatures. Also removes hold spells and slow effects." },
        { name: "Speak with Dead", level: 3, sphere: "Divination", range: "1", duration: "1 rd/level", aoe: "1 creature", components: "V,S,M", casting_time: "1 turn", save: "None", desc: "Caster can ask corpse 1-2 questions per level. Corpse must have mouth and not be undead. Answers are brief and cryptic." },
        { name: "Stone Shape", level: 3, sphere: "Elemental (Earth)", range: "Touch", duration: "Permanent", aoe: "9 cu ft+1 cu ft/level", components: "V,S,M", casting_time: "1 rd", save: "None", desc: "Caster can shape stone into any form. Can create doors, statues, weapons. Fine detail requires proficiency check." },
        { name: "Summon Insects", level: 3, sphere: "Animal", range: "30 yds", duration: "1 rd/level", aoe: "1 creature", components: "V,S,M", casting_time: "1 rd", save: "Neg.", desc: "Summons cloud of insects that attacks one creature. 2 HP damage per round. Creature must save or flee in panic." },
        { name: "Water Breathing", level: 3, sphere: "Elemental (Water)", range: "Touch", duration: "1 hr/level", aoe: "1 creature", components: "V,S", casting_time: "6", save: "None", desc: "Target can breathe underwater. Can be reversed to allow water-breathing creatures to breathe air." },
        { name: "Water Walk", level: 3, sphere: "Elemental (Water)", range: "Touch", duration: "1 turn+1 rd/level", aoe: "1 creature/level", components: "V,S,M", casting_time: "1 rd", save: "None", desc: "Targets can walk on water as if solid ground. Can walk on mud, quicksand, or snow without sinking." }
    ]
,

    wizard_schools: ["Abjuration", "Alteration", "Conjuration", "Divination", "Enchantment", "Evocation", "Illusion", "Necromancy", "Transmutation"],
    priest_spheres: ["All", "Animal", "Astral", "Charm", "Combat", "Creation", "Divination", "Elemental", "Guardian", "Healing", "Necromantic", "Plant", "Protection", "Summoning", "Sun", "Weather", "Chaos", "Law", "War", "Wards"]

};